[book]
title = "The Gist of Rust"
authors = ["Mustafif Khan"]
language = "en"
multilingual = false
src = "src"
[output.html]
preferred-dark-theme = "ayu"
default-theme = "ayu"
git-repository-url = "https://github.com/MKProj/GistOfRust"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/MKProj/GistOfRust/issues/"
copy-fonts = true
no-section-label = false
[output.html.search]
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hieracrhy = 1
boost-paragraph = 1 
expand = true 
heading-split-level = 3
copy-js = true 
